env_id: 2DBpp-v4
n_envs: 5
train_seed: 0
eval_seed: 10
total_timesteps: 10000
n_eval_episodes: 50
n_eval_seeds: 20
log_dir: logs/ppo
env_kwargs:
  render_mode: human
  bin_channels: 3
  min_items_per_bin: 20
  max_items_per_bin: 30
  area_reward_coef: 0.4
  constant_penalty: -5.0
  action_fail: continue
  reward_type: area
monitor_kwargs:
  info_keywords: !!python/tuple
  - PE
PPO_kwargs:
  learning_rate: 0.0001
  clip_range: 0.02
ACKTR_kwargs:
  learning_rate: 0.0001