env_id: 2DBpp-v1
n_envs: 4
train_seed: 0
eval_seed: 10
total_timesteps: 1200000
n_eval_episodes: 20
log_dir: logs/ppo
reward_type: area
env_kwargs:
  render_mode: human
  bin_channels: 3
  items_per_bin: 12
  area_reward_coef: 0.4
  constant_penalty: -5.0
  action_fail: continue
monitor_kwargs:
  info_keywords: !!python/tuple
  - PE
policy_kwargs: &id001
  normalize_images: false
  network: CnnMlpNetwork1
  network_kwargs:
    hidden_dim: 100
  dist_kwargs:
    mask_strategy: replace
    mask_minus_coef: 15
    mask_replace_coef: -15
    update_actor_stratrgy: masked
    entropy_strategy: naive
    invalid_probs_strategy: naive
PPO_kwargs:
  policy: CnnMlpPolicy
  learning_rate: 0.001
  n_steps: 128
  batch_size: 64
  n_epochs: 1
  gamma: 0.99
  gae_lambda: 0.98
  clip_range: 0.4
  normalize_advantage: true
  vf_coef: 0.5
  max_grad_norm: 5
  stats_window_size: 100
  policy_kwargs: *id001
  verbose: 1
  seed: 0
  add_mask_loss: true
  mask_coef: 0.5
  add_entropy_loss: true
  ent_coef: 0.01
  add_invalid_probs: true
  invalid_probs_coef: 0.01
